name: Docker Publish Workflow

on:
  workflow_call:
    inputs:
      docker_username:
        description: Docker username
        required: true
        type: string

      docker_password:
        required: true
        description: Docker password
        type: string

      docker_image_name:
        required: true
        description: Docker Image Name
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ inputs.docker_image_name }} .

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}

      - name: Docker Push image
        run: docker push ${{ inputs.docker_image_name }}
