name: Docker Publish Workflow

on:
  workflow_call:
    secrets:
      docker_username:
        description: Docker username
        required: true

      docker_password:
        required: true
        description: Docker password

    inputs:
      tag:
        description: Image tag name
        type: string

      image_name:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Docker Build and Push image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{secrets.docker_username}}/${{ inputs.image_name }}:${{ inputs.tag }}
